timeout = 30
retry_wait_time = 5
max_retries = 6
max_concurrency = 4

# Check link anchors
include_fragments = true

# Use a custom user agent to prevent being blocked by Splunk docs site
user_agent = 'User-Agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0'

exclude = [
  '^https://developers.redhat.com/download-manager/file/jboss-eap-.*.zip',
  '^http://localhost.*',
  '^https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/com/splunk/',
]
