name: publish-profiling-petclinic-base-image
on: workflow_dispatch
jobs:
  push_to_registry_linux:
    name: publish custom linux spring-petclinic base image for profiling
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_version: [8, 11, 17]
    permissions:
      packages: write
      contents: read
    steps:
      - name: check out the repo
        uses: actions/checkout@v3.2.0
      - uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push to gh packages
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          file: smoke-tests/profiling-base-petclinic/linux/Dockerfile
          build-args: |
            jdkVersion=${{ matrix.jdk_version }}
          tags: ghcr.io/signalfx/splunk-otel-java/profiling-petclinic-base-linux-jdk${{ matrix.jdk_version }}:latest
  push_to_registry_windows:
    name: publish custom windows spring-petclinic base image for profiling
    runs-on: windows-2019
    strategy:
      matrix:
        jdk_version: [8, 11, 17]
    defaults:
      run:
        shell: bash
    permissions:
      packages: write
      contents: read
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - name: check out the repo
        uses: actions/checkout@v3.2.0
      - name: Login to GitHub Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push docker image
        run: ./build.sh ${{ matrix.jdk_version }}
        working-directory: smoke-tests/profiling-base-petclinic/windows
